word_replacements = {
    "nao": "não",
    # "agua": "água",
    # "coracao": "coração",
    # "leao": "leão",
    # "maquina": "máquina",
    # "ocasiao": "ocasião",
    # "pagina": "página",
    # "paixao": "paixão",
    # "comodo": "cômodo",
    # "facil": "fácil",
    # "ceu": "céu",
    # "gratis": "grátis",
    # "mes": "mês",
    # "animo": "ânimo",
    # "album": "álbum",
    # "serie": "série",
    # "unico": "único",
    # "pratico": "prático",
    # "regua": "régua",
    # "virus": "vírus",
    # "poetico": "poético",
    # "televisao": "televisão",
    # "maca": "maçã",
    # "direcao": "direção",
    # "inovador": "inovador",
    # "violao": "violão",
    # "relogio": "relógio",
    # Add more words as needed
}
